#
# @author darryl.west <darryl.west@raincitysoftware.com>
# @created 2017-09-26 12:12:40
#

FROM scratch

LABEL maintainer="darryl.west@raincitysoftware.com"

EXPOSE 80

COPY unique-tcp /unique-tcp

CMD [ "/unique-tcp", "--port", "80" ]

